<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ScreenStat.Core</RootNamespace>
    <AssemblyName>ScreenStat.Core</AssemblyName>
  </PropertyGroup>
</Project>
