//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenStat.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenStat.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenStat
        ///Select an area on screen, recognize it, count the numbers.
        ///Everything runs locally; nothing is uploaded.
        ///Hotkey: {0}.
        /// </summary>
        public static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenStat.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture failed: {0}.
        /// </summary>
        public static string CaptureFailed {
            get {
                return ResourceManager.GetString("CaptureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write to the clipboard..
        /// </summary>
        public static string ClipboardFailed {
            get {
                return ResourceManager.GetString("ClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0}.
        /// </summary>
        public static string ColumnHeader {
            get {
                return ResourceManager.GetString("ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enabled numbers in this column.
        /// </summary>
        public static string ColumnNoValidNumbers {
            get {
                return ResourceManager.GetString("ColumnNoValidNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0} numbers.
        /// </summary>
        public static string ColumnUsing {
            get {
                return ResourceManager.GetString("ColumnUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0} numbers, {1} malformed.
        /// </summary>
        public static string ColumnUsingWithInvalid {
            get {
                return ResourceManager.GetString("ColumnUsingWithInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CommonClose {
            get {
                return ResourceManager.GetString("CommonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CommonCopy {
            get {
                return ResourceManager.GetString("CommonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        public static string GridConfidence {
            get {
                return ResourceManager.GetString("GridConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string GridOrigin {
            get {
                return ResourceManager.GetString("GridOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string GridStatus {
            get {
                return ResourceManager.GetString("GridStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string GridUse {
            get {
                return ResourceManager.GetString("GridUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized number (editable).
        /// </summary>
        public static string GridValue {
            get {
                return ResourceManager.GetString("GridValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both local engines failed. ONNX: {0}. Windows OCR: {1}..
        /// </summary>
        public static string OcrBothEnginesFailed {
            get {
                return ResourceManager.GetString("OcrBothEnginesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captured image is empty, nothing to recognize..
        /// </summary>
        public static string OcrEmptyImage {
            get {
                return ResourceManager.GetString("OcrEmptyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR failed: {0}.
        /// </summary>
        public static string OcrFailedWithReason {
            get {
                return ResourceManager.GetString("OcrFailedWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local ONNX OCR could not finish, so Windows OCR was used instead. Reason: {0}.
        /// </summary>
        public static string OcrFallbackWarning {
            get {
                return ResourceManager.GetString("OcrFallbackWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR returned no text..
        /// </summary>
        public static string OcrNoText {
            get {
                return ResourceManager.GetString("OcrNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text regions were detected..
        /// </summary>
        public static string OcrNoTextRegions {
            get {
                return ResourceManager.GetString("OcrNoTextRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local ONNX recognition failed: {0}.
        /// </summary>
        public static string OcrOnnxFailed {
            get {
                return ResourceManager.GetString("OcrOnnxFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw output from the recognition engine, before column splitting or number parsing..
        /// </summary>
        public static string OcrTextHint {
            get {
                return ResourceManager.GetString("OcrTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR text.
        /// </summary>
        public static string OcrTextTitle {
            get {
                return ResourceManager.GetString("OcrTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error.
        /// </summary>
        public static string OcrUnknownError {
            get {
                return ResourceManager.GetString("OcrUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the Windows OCR engine. Install the Optical character recognition language pack for English or Chinese under Settings, Time and language, Language and region..
        /// </summary>
        public static string OcrWindowsEngineUnavailable {
            get {
                return ResourceManager.GetString("OcrWindowsEngineUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows OCR failed..
        /// </summary>
        public static string OcrWindowsFailed {
            get {
                return ResourceManager.GetString("OcrWindowsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows OCR returned no text..
        /// </summary>
        public static string OcrWindowsNoText {
            get {
                return ResourceManager.GetString("OcrWindowsNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy numbers.
        /// </summary>
        public static string ResultCopyNumbers {
            get {
                return ResourceManager.GetString("ResultCopyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy stats.
        /// </summary>
        public static string ResultCopyStatistics {
            get {
                return ResourceManager.GetString("ResultCopyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local only · nothing uploaded · uncheck a row to exclude it.
        /// </summary>
        public static string ResultFooter {
            get {
                return ResourceManager.GetString("ResultFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the local recognition model....
        /// </summary>
        public static string ResultLoading {
            get {
                return ResourceManager.GetString("ResultLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} low confidence.
        /// </summary>
        public static string ResultLowConfidenceFormat {
            get {
                return ResourceManager.GetString("ResultLowConfidenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter one number per line, for example 12.5 or 123ms..
        /// </summary>
        public static string ResultManualEntryHint {
            get {
                return ResourceManager.GetString("ResultManualEntryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No numbers found.
        /// </summary>
        public static string ResultNoNumbers {
            get {
                return ResourceManager.GetString("ResultNoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR returned text, but nothing countable. Open OCR text to see what it read..
        /// </summary>
        public static string ResultOcrNoCountableNumbers {
            get {
                return ResourceManager.GetString("ResultOcrNoCountableNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR returned no text..
        /// </summary>
        public static string ResultOcrReturnedNoText {
            get {
                return ResourceManager.GetString("ResultOcrReturnedNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition failed.
        /// </summary>
        public static string ResultRecognitionFailed {
            get {
                return ResourceManager.GetString("ResultRecognitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognizing....
        /// </summary>
        public static string ResultRecognizing {
            get {
                return ResourceManager.GetString("ResultRecognizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} columns, {1} numbers.
        /// </summary>
        public static string ResultStatusColumns {
            get {
                return ResourceManager.GetString("ResultStatusColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numbers.
        /// </summary>
        public static string ResultStatusNumbers {
            get {
                return ResourceManager.GetString("ResultStatusNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} to review.
        /// </summary>
        public static string ResultStatusReviewSuffix {
            get {
                return ResourceManager.GetString("ResultStatusReviewSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string RowAdded {
            get {
                return ResourceManager.GetString("RowAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        public static string RowEdited {
            get {
                return ResourceManager.GetString("RowEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string RowExcluded {
            get {
                return ResourceManager.GetString("RowExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed.
        /// </summary>
        public static string RowMalformed {
            get {
                return ResourceManager.GetString("RowMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string RowReview {
            get {
                return ResourceManager.GetString("RowReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to select an area · ESC to cancel.
        /// </summary>
        public static string SelectionHint {
            get {
                return ResourceManager.GetString("SelectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string SettingsHotkey {
            get {
                return ResourceManager.GetString("SettingsHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey is now {0}..
        /// </summary>
        public static string SettingsHotkeyApplied {
            get {
                return ResourceManager.GetString("SettingsHotkeyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the box, then press the combination you want. It must include Ctrl, Alt or Shift..
        /// </summary>
        public static string SettingsHotkeyHint {
            get {
                return ResourceManager.GetString("SettingsHotkeyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current hotkey is not registered. Pick another combination..
        /// </summary>
        public static string SettingsHotkeyInactive {
            get {
                return ResourceManager.GetString("SettingsHotkeyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination must include Ctrl, Alt or Shift..
        /// </summary>
        public static string SettingsHotkeyNeedsModifier {
            get {
                return ResourceManager.GetString("SettingsHotkeyNeedsModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a combination....
        /// </summary>
        public static string SettingsHotkeyPressPrompt {
            get {
                return ResourceManager.GetString("SettingsHotkeyPressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use by another program. The previous hotkey is still active..
        /// </summary>
        public static string SettingsHotkeyTaken {
            get {
                return ResourceManager.GetString("SettingsHotkeyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to windows opened from now on..
        /// </summary>
        public static string SettingsLanguageNote {
            get {
                return ResourceManager.GetString("SettingsLanguageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string SettingsLanguageSystem {
            get {
                return ResourceManager.GetString("SettingsLanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenStat failed to start:
        ///{0}
        ///
        ///Details were written to %TEMP%\ScreenStat-startup.log.
        /// </summary>
        public static string StartupFailed {
            get {
                return ResourceManager.GetString("StartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global hotkey {0} could not be registered — another program is probably using it.
        ///
        ///ScreenStat still works: use Capture and count in the tray menu, or pick a different hotkey in Settings..
        /// </summary>
        public static string StartupHotkeyFailed {
            get {
                return ResourceManager.GetString("StartupHotkeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TrayAbout {
            get {
                return ResourceManager.GetString("TrayAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture and count.
        /// </summary>
        public static string TrayCapture {
            get {
                return ResourceManager.GetString("TrayCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TraySettings {
            get {
                return ResourceManager.GetString("TraySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenStat - {0}.
        /// </summary>
        public static string TrayTooltip {
            get {
                return ResourceManager.GetString("TrayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenStat - hotkey unavailable, use this menu.
        /// </summary>
        public static string TrayTooltipHotkeyUnavailable {
            get {
                return ResourceManager.GetString("TrayTooltipHotkeyUnavailable", resourceCulture);
            }
        }
    }
}
